package if_core_034.train_desk;

import if_core_034.train_desk.entity.*;
import if_core_034.train_desk.service.ClientService;
import if_core_034.train_desk.entity.ClientFactory;
import if_core_034.train_desk.service.StationService;

import if_core_034.train_desk.strategy.ClientGenerationStrategy;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.time.LocalTime;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class ClientServiceTest {

    @Mock
    private ClientFactory clientFactory;

    @Mock
    private StationService stationService;

    private ClientService clientService;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
        clientService = new ClientService(clientFactory, stationService);
    }

    @Test
    void testGenerateClient() {
        Client mockClient = mock(Client.class);
        when(clientFactory.generateClient()).thenReturn(mockClient);

        Client client = clientService.generateClient();

        assertNotNull(client, "Generated client should not be null");
        assertSame(mockClient, client, "Client should match the one generated by ClientFactory");
        verify(clientFactory, times(1)).generateClient();
    }

    @Test
    void testGetNextArrivalTimeWithValidStrategy() {
        ClientGenerationStrategy mockStrategy = mock(ClientGenerationStrategy.class);
        when(clientFactory.getClientGenerationStrategy()).thenReturn(mockStrategy);
        when(mockStrategy.getNextArrivalTime()).thenReturn(LocalTime.of(10, 30));

        Long arrivalTime = clientService.getNextArrivalTime();

        assertEquals(10 * 3600 * 1000 + 30 * 60 * 1000, arrivalTime, "Arrival time should match the converted time");
    }

    @Test
    void testGetNextArrivalTimeWithNullStrategy() {
        ClientGenerationStrategy mockStrategy = mock(ClientGenerationStrategy.class);
        when(clientFactory.getClientGenerationStrategy()).thenReturn(mockStrategy);
        when(mockStrategy.getNextArrivalTime()).thenReturn(null);

        Long arrivalTime = clientService.getNextArrivalTime();

        assertEquals(5000L, arrivalTime, "Arrival time should default to 5000ms when strategy returns null");
    }

    @Test
    void testGetBestCashRegisterId() {
        Station mockStation = mock(Station.class);
        Map<Integer, CashDesk> mockCashDesks = Map.of(
                1, createMockCashDesk(1, true, 5, new Position(0, 0)),
                2, createMockCashDesk(2, true, 3, new Position(3, 4)) // Closer with a smaller queue
        );
        Client mockClient = mock(Client.class);
        when(mockClient.getPosition()).thenReturn(new Position(1, 1));
        when(stationService.getStationInstance()).thenReturn(mockStation);
        when(mockStation.getCashDeskMap()).thenReturn(mockCashDesks);

        int bestCashRegisterId = clientService.getBestCashRegisterId(mockClient);

        assertEquals(2, bestCashRegisterId, "Best cash register ID should be 2 based on distance and queue");
    }

    private CashDesk createMockCashDesk(int id, boolean operational, int queuePosition, Position position) {
        CashDesk mockCashDesk = mock(CashDesk.class);
        when(mockCashDesk.getId()).thenReturn(id);
        when(mockCashDesk.isOperational()).thenReturn(operational);
        when(mockCashDesk.getPotentialQueuePosition(any())).thenReturn((long) queuePosition);
        when(mockCashDesk.getPosition()).thenReturn(position);
        return mockCashDesk;
    }

}
